name: "event_fusion"
version: "1.0.0"
config-version: 2

profile: "event_fusion"

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  event_fusion:
    silver:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
